apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: app-deployment
  labels: 
    app: node-backend
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: node-backend 
  template: 
    metadata:
      name: my-app
      labels: 
        app: node-backend 
    spec:
      containers:
        - name: node-backend 
          image: guruhbk/expertinterview:1
          ports:
            - containerPort: 8080
              protocol: TCP 
          resources:
            requests: 
              cpu: 100m
              memory: 500Mi
            limits: 
              cpu: 200m
              memory: 2Gi
          securityContext: 
            # runAsNonRootUser: true
            runAsUser: 1001
            runAsGroup: 1001
      imagePullSecrets: 
       - name: regcred