name: ci-pipline
on:
    workflow_dispatch:
        inputs: 
            tag: 
                required: true
                description: tag of the image


env:
    reponame: guruhbk/expertinterview

jobs:
    security-scan:
        runs-on: ubuntu-latest
        steps:
            - name: code-checkout
              uses: actions/checkout@v4
            - name: npm-test
              run: |
                export NODE_ENV=test
                npm i
                npm run test
    
    docker-build-push:
        runs-on: ubuntu-latest
        needs: security-scan
        steps:
            - name: code-checkout
              uses: actions/checkout@v4
            - name: docker-login
              run:  docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
            - name: docker-build 
              run: docker build -f ./Dockerfile -t "${{env.reponame}}:${{github.event.inputs.tag}}" .
            - name: docker push
              run: docker push "${{env.reponame}}:${{github.event.inputs.tag}}"
